"""add_rag_2_fields

Revision ID: 2a1a5f704789
Revises: 633a3a32197a
Create Date: 2026-09-22 14:17:20.046134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1a5f704789'
down_revision: Union[str, Sequence[str], None] = '633a3a32197a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mime_type', sa.String(), server_default='text/plain', nullable=False))
        batch_op.add_column(sa.Column('file_size', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='ready', nullable=False))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('error_message', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('metadata_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('metadata_json')
        batch_op.drop_column('error_message')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('status')
        batch_op.drop_column('file_size')
        batch_op.drop_column('mime_type')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
