"""add_memory_2_fields

Revision ID: 633a3a32197a
Revises: 7c123f4eb1bb
Create Date: 2026-09-21 23:05:51.387957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633a3a32197a'
down_revision: Union[str, Sequence[str], None] = '7c123f4eb1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('memory_type', sa.String(), server_default='preference', nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(), server_default='explicit_user', nullable=False))
        batch_op.add_column(sa.Column('confidence', sa.String(), server_default='high', nullable=False))
        batch_op.add_column(sa.Column('importance', sa.String(), server_default='medium', nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='active', nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('access_count', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_column('access_count')
        batch_op.drop_column('last_accessed_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('status')
        batch_op.drop_column('importance')
        batch_op.drop_column('confidence')
        batch_op.drop_column('source')
        batch_op.drop_column('memory_type')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
