import type {
  MemoryItem,
  Agent,
  KnowledgeDoc,
  KnowledgeNode,
  KnowledgeEdge,
  Conversation,
  LLMModel,
  ActivityItem,
  StatCard,
  PricingTier,
} from './types';

export const navItems = [
  { label: 'Dashboard', href: '/dashboard', icon: 'LayoutDashboard' },
  { label: 'AI Chat', href: '/chat', icon: 'MessageSquare' },
  { label: 'Agents', href: '/agents', icon: 'Bot' },
  { label: 'Memory', href: '/memory', icon: 'BrainCircuit' },
  { label: 'Knowledge', href: '/knowledge', icon: 'BookOpen' },
  { label: 'Analytics', href: '/analytics', icon: 'BarChart3' },
  { label: 'Settings', href: '/settings', icon: 'Settings' },
] as const;

export const dashboardStats: StatCard[] = [
  {
    id: 'ai-activity',
    label: 'AI Activity',
    value: '12,847',
    change: '+18.2%',
    trend: 'up',
    icon: 'Activity',
    sparkline: [30, 45, 38, 52, 60, 48, 72, 80, 65, 88, 92, 100],
  },
  {
    id: 'agent-exec',
    label: 'Agent Executions',
    value: '3,492',
    change: '+24.6%',
    trend: 'up',
    icon: 'Bot',
    sparkline: [20, 35, 40, 30, 55, 62, 50, 68, 75, 70, 85, 95],
  },
  {
    id: 'memory-growth',
    label: 'Memory Growth',
    value: '8,206',
    change: '+12.4%',
    trend: 'up',
    icon: 'BrainCircuit',
    sparkline: [40, 42, 48, 55, 50, 60, 65, 62, 70, 78, 82, 90],
  },
  {
    id: 'knowledge-db',
    label: 'Knowledge Base',
    value: '2,318',
    change: '+8.1%',
    trend: 'up',
    icon: 'Database',
    sparkline: [25, 30, 35, 42, 48, 45, 52, 58, 60, 65, 72, 78],
  },
  {
    id: 'llm-usage',
    label: 'LLM Calls',
    value: '94,521',
    change: '+31.5%',
    trend: 'up',
    icon: 'Cpu',
    sparkline: [15, 28, 40, 35, 52, 60, 70, 65, 80, 85, 90, 98],
  },
  {
    id: 'productivity',
    label: 'Productivity Score',
    value: '94.2',
    change: '+5.3%',
    trend: 'up',
    icon: 'TrendingUp',
    sparkline: [60, 65, 62, 70, 72, 68, 75, 80, 78, 85, 90, 94],
  },
];

export const activityTimeline: ActivityItem[] = [
  {
    id: 'a1',
    type: 'agent',
    title: 'Research Agent completed analysis',
    description: 'Synthesized 14 sources on market expansion strategy',
    timestamp: '2 min ago',
    status: 'success',
  },
  {
    id: 'a2',
    type: 'chat',
    title: 'New conversation with Claude 3.5',
    description: 'Code review session started — 3 files analyzed',
    timestamp: '8 min ago',
    status: 'info',
  },
  {
    id: 'a3',
    type: 'memory',
    title: 'Memory updated: Project Aurora',
    description: 'Stored 5 key decisions and 2 preference updates',
    timestamp: '14 min ago',
    status: 'success',
  },
  {
    id: 'a4',
    type: 'knowledge',
    title: 'Indexing document: Q3 Financial Report',
    description: 'Generated 128 vector embeddings from 42-page PDF',
    timestamp: '23 min ago',
    status: 'running',
  },
  {
    id: 'a5',
    type: 'automation',
    title: 'Workflow triggered: Daily Digest',
    description: 'Compiled overnight activity into summary report',
    timestamp: '1 hr ago',
    status: 'success',
  },
  {
    id: 'a6',
    type: 'agent',
    title: 'Planning Agent built execution plan',
    description: '7-step plan for customer onboarding automation',
    timestamp: '2 hr ago',
    status: 'info',
  },
  {
    id: 'a7',
    type: 'system',
    title: 'LLM fallback activated',
    description: 'Routed request from GPT-4o to Claude 3.5 after timeout',
    timestamp: '3 hr ago',
    status: 'warning',
  },
];

export const memoryItems: MemoryItem[] = [
  {
    id: 'm1',
    title: 'Project Aurora — North Star Metric',
    description:
      'Primary success metric is weekly active power users. Team agreed to prioritize onboarding flow over feature breadth in Q4.',
    category: 'Projects',
    importance: 'Critical',
    createdAt: '2025-07-28',
    relevanceScore: 98,
    tags: ['product', 'metrics', 'Q4'],
  },
  {
    id: 'm2',
    title: 'Build in public preference',
    description:
      'User prefers transparent, public development updates. Favors sharing progress milestones on X and LinkedIn weekly.',
    category: 'Preferences',
    importance: 'High',
    createdAt: '2025-07-26',
    relevanceScore: 91,
    tags: ['communication', 'social'],
  },
  {
    id: 'm3',
    title: 'Master React Server Components',
    description:
      'Ongoing learning goal. Completed advanced patterns course. Next: streaming SSR with Suspense boundaries.',
    category: 'Skills',
    importance: 'High',
    createdAt: '2025-07-22',
    relevanceScore: 87,
    tags: ['react', 'frontend', 'learning'],
  },
  {
    id: 'm4',
    title: 'Ship MVP by September 30',
    description:
      'Hard deadline. Key features: AI chat, memory, knowledge base, 3 agents. Stretch: automation builder.',
    category: 'Goals',
    importance: 'Critical',
    createdAt: '2025-07-15',
    relevanceScore: 95,
    tags: ['deadline', 'mvp', 'roadmap'],
  },
  {
    id: 'm5',
    title: 'TypeScript strict mode policy',
    description:
      'All new code must pass strict type checking. No `any` types. Use unknown + type guards for external data.',
    category: 'Preferences',
    importance: 'Medium',
    createdAt: '2025-07-12',
    relevanceScore: 72,
    tags: ['typescript', 'code-quality'],
  },
  {
    id: 'm6',
    title: 'Vector embedding architecture',
    description:
      'Knowledge base uses pgvector with 1536-dim embeddings. HNSW index, cosine similarity, chunk size 512 tokens.',
    category: 'Knowledge',
    importance: 'High',
    createdAt: '2025-07-10',
    relevanceScore: 89,
    tags: ['rag', 'embeddings', 'postgres'],
  },
  {
    id: 'm7',
    title: 'Customer: Acme Corp requirements',
    description:
      'Needs SSO, SOC2 compliance, custom model routing. 50 seats. Decision by Aug 15. Champion: VP Engineering.',
    category: 'Projects',
    importance: 'High',
    createdAt: '2025-07-08',
    relevanceScore: 84,
    tags: ['enterprise', 'sales', 'security'],
  },
  {
    id: 'm8',
    title: 'Prefers concise, code-first answers',
    description:
      'In chat interactions, user values direct code examples over lengthy explanations. Skip preamble.',
    category: 'Preferences',
    importance: 'Medium',
    createdAt: '2025-07-05',
    relevanceScore: 78,
    tags: ['chat', 'communication-style'],
  },
  {
    id: 'm9',
    title: 'LangGraph orchestration pattern',
    description:
      'Agents use LangGraph state machines for multi-step reasoning. Checkpointing enables pause/resume and human-in-the-loop.',
    category: 'Knowledge',
    importance: 'Medium',
    createdAt: '2025-07-02',
    relevanceScore: 80,
    tags: ['agents', 'orchestration', 'langgraph'],
  },
  {
    id: 'm10',
    title: 'Run a half marathon by December',
    description:
      'Fitness goal. Currently at 10K distance. Training 3x/week. Schedule: speed Tues, long run Sat, easy Thurs.',
    category: 'Goals',
    importance: 'Low',
    createdAt: '2025-06-28',
    relevanceScore: 61,
    tags: ['fitness', 'personal'],
  },
  {
    id: 'm11',
    title: 'Design system: 8px grid, dark-first',
    description:
      'All UI follows 8px spacing system. Dark theme is primary. Glassmorphism for elevated surfaces. Max 3 font weights.',
    category: 'Knowledge',
    importance: 'Medium',
    createdAt: '2025-06-25',
    relevanceScore: 74,
    tags: ['design', 'ui', 'system'],
  },
  {
    id: 'm12',
    title: 'Prefers morning deep work blocks',
    description:
      'Highest focus 9am-12pm. Schedule meetings after 2pm. Avoid notifications during deep work blocks.',
    category: 'Preferences',
    importance: 'Medium',
    createdAt: '2025-06-20',
    relevanceScore: 70,
    tags: ['schedule', 'productivity'],
  },
];

export const agents: Agent[] = [
  {
    id: 'ag1',
    name: 'Atlas',
    description: 'Strategic planning and research agent. Excels at multi-source synthesis.',
    status: 'Executing',
    avatar: 'A',
    tasksCompleted: 847,
    successRate: 97.4,
    lastActive: 'Active now',
    tools: ['Web Search', 'Knowledge RAG', 'Code Interpreter', 'Memory Recall'],
    currentTask: 'Researching competitive landscape for Project Aurora',
    steps: [
      { id: 's1', label: 'Parse objective', status: 'done', tool: 'Planner', detail: 'Decomposed into 4 sub-goals' },
      { id: 's2', label: 'Retrieve knowledge', status: 'done', tool: 'RAG', detail: 'Found 14 relevant documents' },
      { id: 's3', label: 'Web research', status: 'active', tool: 'Web Search', detail: 'Querying 6 sources...' },
      { id: 's4', label: 'Synthesize findings', status: 'pending', detail: 'Pending data collection' },
      { id: 's5', label: 'Generate report', status: 'pending', detail: 'Pending synthesis' },
    ],
  },
  {
    id: 'ag2',
    name: 'Nova',
    description: 'Code generation and engineering agent. Full-stack development and debugging.',
    status: 'Active',
    avatar: 'N',
    tasksCompleted: 1234,
    successRate: 95.1,
    lastActive: '3 min ago',
    tools: ['Code Interpreter', 'File System', 'Git', 'Test Runner', 'Linter'],
    currentTask: 'Refactoring authentication module',
    steps: [
      { id: 's1', label: 'Analyze codebase', status: 'done', tool: 'Code Interpreter', detail: 'Mapped 23 files' },
      { id: 's2', label: 'Identify issues', status: 'done', tool: 'Linter', detail: 'Found 8 issues' },
      { id: 's3', label: 'Apply fixes', status: 'active', tool: 'File System', detail: 'Refactoring 3 files...' },
      { id: 's4', label: 'Run tests', status: 'pending', detail: 'Pending changes' },
    ],
  },
  {
    id: 'ag3',
    name: 'Sage',
    description: 'Document intelligence agent. Parsing, extraction, and knowledge indexing.',
    status: 'Planning',
    avatar: 'S',
    tasksCompleted: 562,
    successRate: 99.2,
    lastActive: '12 min ago',
    tools: ['PDF Parser', 'OCR', 'Embedding Engine', 'Vector DB'],
    currentTask: 'Indexing Q3 financial documents',
    steps: [
      { id: 's1', label: 'Receive documents', status: 'done', detail: '12 files received' },
      { id: 's2', label: 'Plan extraction', status: 'active', tool: 'Planner', detail: 'Determining chunk strategy' },
      { id: 's3', label: 'Extract & embed', status: 'pending', detail: 'Pending plan' },
      { id: 's4', label: 'Store vectors', status: 'pending', detail: 'Pending extraction' },
    ],
  },
  {
    id: 'ag4',
    name: 'Echo',
    description: 'Automation and workflow agent. Connects tools and orchestrates pipelines.',
    status: 'Active',
    avatar: 'E',
    tasksCompleted: 2103,
    successRate: 98.8,
    lastActive: '1 min ago',
    tools: ['Webhook', 'API Client', 'Scheduler', 'Email', 'Slack'],
    currentTask: 'Monitoring 4 active automations',
    steps: [
      { id: 's1', label: 'Poll triggers', status: 'active', tool: 'Scheduler', detail: '4 workflows running' },
      { id: 's2', label: 'Execute actions', status: 'pending', detail: 'Awaiting triggers' },
    ],
  },
  {
    id: 'ag5',
    name: 'Pulse',
    description: 'Analytics and insights agent. Monitors metrics and surfaces anomalies.',
    status: 'Idle',
    avatar: 'P',
    tasksCompleted: 689,
    successRate: 96.3,
    lastActive: '45 min ago',
    tools: ['SQL Query', 'Chart Builder', 'Alert System'],
  },
  {
    id: 'ag6',
    name: 'Vista',
    description: 'Creative and content agent. Writing, design suggestions, and brainstorming.',
    status: 'Paused',
    avatar: 'V',
    tasksCompleted: 421,
    successRate: 94.7,
    lastActive: '2 hr ago',
    tools: ['Text Generator', 'Image Prompt', 'Style Guide'],
  },
];

export const knowledgeDocs: KnowledgeDoc[] = [
  { id: 'k1', title: 'Q3 Financial Report', type: 'PDF', chunks: 128, vectors: 128, status: 'Indexed', uploadedAt: '2025-07-30', size: '4.2 MB' },
  { id: 'k2', title: 'Product Requirements — Aurora', type: 'Note', chunks: 34, vectors: 34, status: 'Indexed', uploadedAt: '2025-07-28', size: '128 KB' },
  { id: 'k3', title: 'API Reference Documentation', type: 'Web', chunks: 212, vectors: 212, status: 'Indexed', uploadedAt: '2025-07-25', size: '—' },
  { id: 'k4', title: 'Customer Interview Notes', type: 'Note', chunks: 56, vectors: 56, status: 'Indexed', uploadedAt: '2025-07-22', size: '340 KB' },
  { id: 'k5', title: 'auth-service.ts', type: 'Code', chunks: 18, vectors: 18, status: 'Indexed', uploadedAt: '2025-07-20', size: '24 KB' },
  { id: 'k6', title: 'Market Analysis 2025', type: 'PDF', chunks: 95, vectors: 0, status: 'Processing', uploadedAt: '2025-08-01', size: '2.8 MB' },
  { id: 'k7', title: 'User Behavior Dataset', type: 'Data', chunks: 340, vectors: 340, status: 'Indexed', uploadedAt: '2025-07-18', size: '12.4 MB' },
  { id: 'k8', title: 'Brand Guidelines v2', type: 'PDF', chunks: 42, vectors: 42, status: 'Indexed', uploadedAt: '2025-07-15', size: '8.1 MB' },
];

export const knowledgeNodes: KnowledgeNode[] = [
  { id: 'n0', label: 'RajOS Core', group: 'core' },
  { id: 'n1', label: 'AI Agents', group: 'domain' },
  { id: 'n2', label: 'Memory Engine', group: 'domain' },
  { id: 'n3', label: 'Knowledge Base', group: 'domain' },
  { id: 'n4', label: 'LLM Router', group: 'domain' },
  { id: 'n5', label: 'Automation', group: 'domain' },
  { id: 'd1', label: 'Atlas Agent', group: 'document' },
  { id: 'd2', label: 'Nova Agent', group: 'document' },
  { id: 'd3', label: 'Project Aurora', group: 'document' },
  { id: 'd4', label: 'Q3 Finances', group: 'document' },
  { id: 'd5', label: 'API Docs', group: 'document' },
  { id: 'c1', label: 'Planning', group: 'concept' },
  { id: 'c2', label: 'RAG Retrieval', group: 'concept' },
  { id: 'c3', label: 'Vector Search', group: 'concept' },
  { id: 'c4', label: 'Embeddings', group: 'concept' },
  { id: 'c5', label: 'Routing', group: 'concept' },
  { id: 'c6', label: 'Workflows', group: 'concept' },
];

export const knowledgeEdges: KnowledgeEdge[] = [
  { source: 'n0', target: 'n1', weight: 1 },
  { source: 'n0', target: 'n2', weight: 1 },
  { source: 'n0', target: 'n3', weight: 1 },
  { source: 'n0', target: 'n4', weight: 1 },
  { source: 'n0', target: 'n5', weight: 1 },
  { source: 'n1', target: 'd1', weight: 0.8 },
  { source: 'n1', target: 'd2', weight: 0.8 },
  { source: 'n1', target: 'c1', weight: 0.6 },
  { source: 'n2', target: 'd3', weight: 0.7 },
  { source: 'n2', target: 'd4', weight: 0.5 },
  { source: 'n3', target: 'd4', weight: 0.8 },
  { source: 'n3', target: 'd5', weight: 0.7 },
  { source: 'n3', target: 'c2', weight: 0.9 },
  { source: 'n3', target: 'c3', weight: 0.8 },
  { source: 'n3', target: 'c4', weight: 0.7 },
  { source: 'n4', target: 'c5', weight: 0.9 },
  { source: 'n5', target: 'c6', weight: 0.9 },
  { source: 'c2', target: 'c3', weight: 0.7 },
  { source: 'c3', target: 'c4', weight: 0.8 },
  { source: 'd1', target: 'c1', weight: 0.6 },
];

export const conversations: Conversation[] = [
  {
    id: 'conv1',
    title: 'Project Aurora architecture',
    lastMessage: 'I recommend a modular monolith with...',
    timestamp: '2 min ago',
    model: 'Claude 3.5 Sonnet',
    agent: 'Atlas',
    messages: [
      {
        id: 'msg1',
        role: 'user',
        content: 'Help me design the architecture for Project Aurora. It needs to handle real-time AI agent orchestration with memory persistence.',
        timestamp: '10:32 AM',
      },
      {
        id: 'msg2',
        role: 'assistant',
        content: 'I recommend a modular monolith with clear bounded contexts for agent orchestration, memory, and knowledge retrieval. For real-time orchestration, an event-driven core using a state machine pattern (like LangGraph) gives you checkpointing and human-in-the-loop pauses. Memory persistence should use PostgreSQL with pgvector — relational data and vector embeddings in the same store simplifies consistency. The key architectural decision is the memory layer: separate hot (recent, in-context) and cold (long-term, retrieval-based) stores to manage token budget efficiently.',
        timestamp: '10:32 AM',
        model: 'Claude 3.5 Sonnet',
        agent: 'Atlas',
        sources: [
          { title: 'LangGraph Documentation', snippet: 'State machines for agent orchestration with checkpointing...' },
          { title: 'pgvector: PostgreSQL Vector Similarity Search', snippet: 'HNSW indexing for sub-50ms retrieval on 1M+ vectors...' },
        ],
        memoryUsed: ['Project Aurora — North Star Metric', 'Vector embedding architecture'],
      },
    ],
  },
  {
    id: 'conv2',
    title: 'Debug auth token refresh',
    lastMessage: 'The issue is in the refresh token...',
    timestamp: '1 hr ago',
    model: 'GPT-4o',
    agent: 'Nova',
    messages: [],
  },
  {
    id: 'conv3',
    title: 'Q3 financial summary',
    lastMessage: 'Revenue is up 34% QoQ driven by...',
    timestamp: '3 hr ago',
    model: 'Claude 3.5 Sonnet',
    agent: 'Sage',
    messages: [],
  },
  {
    id: 'conv4',
    title: 'Automation for daily digest',
    lastMessage: 'I created a workflow that...',
    timestamp: 'Yesterday',
    model: 'GPT-4o',
    agent: 'Echo',
    messages: [],
  },
  {
    id: 'conv5',
    title: 'Content strategy brainstorm',
    lastMessage: 'Here are 5 content pillars aligned...',
    timestamp: 'Yesterday',
    model: 'Claude 3 Opus',
    agent: 'Vista',
    messages: [],
  },
  {
    id: 'conv6',
    title: 'User churn analysis',
    lastMessage: 'Analyzing your retention data...',
    timestamp: '2 days ago',
    model: 'GPT-4o',
    agent: 'Pulse',
    messages: [],
  },
];

export const llmModels: LLMModel[] = [
  { id: 'gpt4o', name: 'GPT-4o', provider: 'OpenAI', contextWindow: '128K', strengths: ['Reasoning', 'Code', 'Vision'], costPerMTok: 5, latency: 'Fast' },
  { id: 'claude35', name: 'Claude 3.5 Sonnet', provider: 'Anthropic', contextWindow: '200K', strengths: ['Analysis', 'Writing', 'Long context'], costPerMTok: 3, latency: 'Fast' },
  { id: 'claude3op', name: 'Claude 3 Opus', provider: 'Anthropic', contextWindow: '200K', strengths: ['Deep reasoning', 'Complex tasks'], costPerMTok: 15, latency: 'Medium' },
  { id: 'gemini15', name: 'Gemini 1.5 Pro', provider: 'Google', contextWindow: '2M', strengths: ['Massive context', 'Multimodal'], costPerMTok: 3.5, latency: 'Medium' },
  { id: 'llama3405', name: 'Llama 3.1 405B', provider: 'Meta', contextWindow: '128K', strengths: ['Open source', 'Cost efficient'], costPerMTok: 2.5, latency: 'Slow' },
  { id: 'mistralL', name: 'Mistral Large', provider: 'Mistral', contextWindow: '128K', strengths: ['European', 'Function calling'], costPerMTok: 4, latency: 'Fast' },
];

export const pricingTiers: PricingTier[] = [
  {
    name: 'Starter',
    price: '$0',
    period: '/mo',
    tagline: 'Explore the operating system',
    features: [
      '3 AI agents',
      '1,000 memory items',
      '50 knowledge documents',
      'Single LLM provider',
      'Community support',
    ],
    cta: 'Start Free',
  },
  {
    name: 'Pro',
    price: '$29',
    period: '/mo',
    tagline: 'For power users and builders',
    features: [
      'Unlimited AI agents',
      '50,000 memory items',
      '1,000 knowledge documents',
      'Multi-LLM smart routing',
      'Automation workflows',
      'Priority support',
    ],
    cta: 'Launch RajOS',
    highlighted: true,
  },
  {
    name: 'Enterprise',
    price: 'Custom',
    period: '',
    tagline: 'For teams and organizations',
    features: [
      'Everything in Pro',
      'Unlimited everything',
      'Custom model fine-tuning',
      'SSO & SAML',
      'SOC2 + audit logs',
      'Dedicated infrastructure',
      '24/7 support + SLA',
    ],
    cta: 'Contact Sales',
  },
];

export const usageChart = [
  { day: 'Mon', chat: 420, agents: 180, memory: 90 },
  { day: 'Tue', chat: 510, agents: 220, memory: 110 },
  { day: 'Wed', chat: 380, agents: 310, memory: 85 },
  { day: 'Thu', chat: 620, agents: 280, memory: 130 },
  { day: 'Fri', chat: 780, agents: 340, memory: 150 },
  { day: 'Sat', chat: 340, agents: 160, memory: 70 },
  { day: 'Sun', chat: 290, agents: 120, memory: 60 },
];

export const llmDistribution = [
  { name: 'GPT-4o', value: 42, color: 'hsl(199, 89%, 56%)' },
  { name: 'Claude 3.5', value: 31, color: 'hsl(189, 94%, 50%)' },
  { name: 'Gemini 1.5', value: 15, color: 'hsl(142, 71%, 45%)' },
  { name: 'Llama 3.1', value: 8, color: 'hsl(38, 92%, 56%)' },
  { name: 'Mistral', value: 4, color: 'hsl(280, 83%, 62%)' },
];

export const memoryGrowthChart = [
  { month: 'Feb', items: 1200 },
  { month: 'Mar', items: 2100 },
  { month: 'Apr', items: 3400 },
  { month: 'May', items: 4800 },
  { month: 'Jun', items: 6100 },
  { month: 'Jul', items: 8206 },
];

export const knowledgeGrowthChart = [
  { month: 'Feb', docs: 120 },
  { month: 'Mar', docs: 340 },
  { month: 'Apr', docs: 680 },
  { month: 'May', docs: 1100 },
  { month: 'Jun', docs: 1650 },
  { month: 'Jul', docs: 2318 },
];

export const productivityChart = [
  { week: 'W1', score: 72 },
  { week: 'W2', score: 78 },
  { week: 'W3', score: 81 },
  { week: 'W4', score: 85 },
  { week: 'W5', score: 88 },
  { week: 'W6', score: 91 },
  { week: 'W7', score: 94 },
  { week: 'W8', score: 96 },
];

export const interactionHistory = [
  { hour: '00', interactions: 12 },
  { hour: '02', interactions: 8 },
  { hour: '04', interactions: 5 },
  { hour: '06', interactions: 14 },
  { hour: '08', interactions: 48 },
  { hour: '10', interactions: 82 },
  { hour: '12', interactions: 64 },
  { hour: '14', interactions: 91 },
  { hour: '16', interactions: 78 },
  { hour: '18', interactions: 56 },
  { hour: '20', interactions: 38 },
  { hour: '22', interactions: 22 },
];
